platform :ios, '13.0'

target 'OpAdxTradPlusDemo' do
  use_frameworks!

  # TradPlus SDK
  pod 'TradPlusAdSDK', '15.1.1'
  pod 'TradPlusAdSDK/TPCrossAdapter', '15.1.1'

  # Opera Ads SDK + TradPlus Adapter
  pod 'OpAdxSdk', '2.12.1'
  pod 'TradPlusOperaSDKAdapter', '2.12.1.0'
end

